spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  config: logback-spring.xml

jwt:
  provider:
    security: soymun
    validate: 3600000
content:
  url: D:\Users\проекты\books\src\main\resources\files